### ISSUE TITLE
The ldflags cannot use shell command

### ISSUE THREAD

**Issue by thank243** [wangyoucao577/go-release-action#152]
This works
workflow code snippet
```
    - name: Get Time
      id: get_time
      run: echo ::set-output name=BuildTime::$(date -Iseconds)
```

`ldflags: -X "github.com/xx/config.date=${{ steps.get_time.outputs.BuildTime }}" -X "github.com/xx/config.version=${{ github.ref_name }}"`

But when I use 
``ldflags: -X "github.com/xx/config.date=$(date -Iseconds)" -X "github.com/xx/config.version=${{ github.ref_name }}"``
The `config.date` will be shown as `$(date -Iseconds)` not time string.

**Comment by wangyoucao577** [comment]
It depends on how Github Action interpreter it. I'm not sure whether it's able to support or not at the moment.      
By the way, there's better way to get the build time instead of `ldflags` now since https://tip.golang.org/doc/go1.18#debug_buildinfo.  See example in https://github.com/wangyoucao577/medialib/blob/main/.github/workflows/release.yml#L32 and https://github.com/wangyoucao577/medialib/blob/main/util/appversion/version.go#L28

**Comment by thank243** [comment]
It's awesome. Thx.
