### ISSUE TITLE
Update the binary on every master commit

### ISSUE THREAD

**Issue by chrislusf** [wangyoucao577/go-release-action#22]
Related to https://github.com/wangyoucao577/go-release-action/issues/11 
The binary is only built on release.

I want to update a binary on every master commit, so that non-Golang users are able to get a binary executable. 

Weekly releasing is not fast enough for some non-Golang users.

**Comment by wangyoucao577** [comment]
The only problem is where would you want to publish the binary to? Without create a new release page, we don't have place to store binaries on Github. Maybe you expect to publish to third party storage?        
Alternativesly, if you're looking for also create release page automatically, refer to the [ohermosa/gorkscrew](https://github.com/ohermosa/gorkscrew/blob/master/.github/workflows/go_build.yml) example in [More-Examples](https://github.com/wangyoucao577/go-release-action/wiki/More-Examples)

**Comment by chrislusf** [comment]
Can we create a "dev" release and always update that binary?

**Comment by chrislusf** [comment]
Is that possible? Thanks!

**Comment by wangyoucao577** [comment]
Yes. I think I can provide one more parameter `upload_url` so that you can always upload binaries to one page.  I may provide it a little later.

**Comment by wangyoucao577** [comment]
@chrislusf  I made a feature branch to support this requirement, please follow below instructions to have a try:            

- Create a release in your repo, e.g., `v0.1.0 Release` (Git Tag `v0.1.0`)
- Use `wangyoucao577/go-release-action@feature/customize-target-release` in your workflow    
- Set additional parameter: `release_tag: v0.1.0`      
- Enable `push` event to trigger your workflow
- Push a commit to your branch, enjoy!     

A little more reference, FYI:     
- Docs to introduce this new parameter: https://github.com/wangyoucao577/go-release-action/tree/feature/customize-target-release
- Active workflow yaml sample: https://github.com/wangyoucao577/vt2geojson/blob/test/customize-release-tag/.github/workflows/release.yml

Let me know whether it's workable for you. I'll merge it once everything works well.

**Comment by chrislusf** [comment]
Can it support a named version, such as "dev" instead of numbered versions?

**Comment by wangyoucao577** [comment]
Something like `{binary_name}-dev-linux-amd64.tar.gz`? Only expect to keep one latest upload?

**Comment by chrislusf** [comment]
Right

**Comment by wangyoucao577** [comment]
Try again with one more parameter `overwrite: true`. And remember to name your tag `dev` since you hope to have the name in asset too.

**Comment by chrislusf** [comment]
Thanks! Seems working. Will test for a few more days.

Another issue: the action is fired for each commit including every pull request. Can I limit it to the "master" branch?

**Comment by chrislusf** [comment]
I am using this here: https://github.com/chrislusf/seaweedfs/releases/tag/dev

However, the description is wrong and misleading: "released this 43 minutes ago · 4 commits to master since this release"

**Comment by wangyoucao577** [comment]
Use
```
  push:
    branches: [ master ]
```
to trigger the pipeline.           

The description "released this 43 minutes ago · 4 commits to master since this release" is for the **release** instead of **release assets**. It means when you create the release and where the git tag in your repo. If you hope it can be refreshed also, you really need the "create release per push -> trigger publish assets per release" combination.      
Alternativesly, add 'date' to assets' name maybe an idea.

**Comment by wangyoucao577** [comment]
@chrislusf  I have merged the changes and released new version `v1.10`. Please switch to either `wangyoucao577/go-release-action@master` or `wangyoucao577/go-release-action@v1.10`. Let me know if any question.

**Comment by chrislusf** [comment]
Done. Can it support adding a built-date to the file name?

**Comment by wangyoucao577** [comment]
No. But I think it's reasonable. I'm considering to add one more parameter that allows you to customize asset name. It will result to many assets by your `push`.      
I have filed another issue to track it, and may provide it a little bit later: https://github.com/wangyoucao577/go-release-action/issues/26. If any detailed expectation, let's discuss in it.      
And I'd like to close this issue first, since the feature has been provided already.     

By the way, you may forgot to update this: https://github.com/chrislusf/seaweedfs/blob/824e96ffcc3903260479b26aa0f27e07fa23a795/.github/workflows/release.yml#L18

**Comment by chrislusf** [comment]
thanks!
