### ISSUE TITLE
Pulling dependencies before build

### ISSUE THREAD

**Issue by BenjaminNavarro** [wangyoucao577/go-release-action#4]
As you suggested me in https://github.com/ngs/go-release.action/issues/6 I tried to use this action to publish my Go binaries.

The issue I face is that the package dependencies are not pulled before build, resulting in the build failure. I also use [actions/setup-go](https://github.com/actions/setup-go) and this one builds my project just fine.

**Comment by wangyoucao577** [comment]
@BenjaminNavarro  Could you please show me the log? Or maybe your action link if it's public?

**Comment by BenjaminNavarro** [comment]
You should be able to check it [here](https://github.com/BenjaminNavarro/docker-manager/actions?query=workflow%3A.github%2Fworkflows%2Frelease.yml)

**Comment by wangyoucao577** [comment]
@BenjaminNavarro  It's due to dependency missing. You didn't use any `Go` dependency management system, so you have to `go get ...` by manual. I have filed a PR for you to fix it: https://github.com/BenjaminNavarro/docker-manager/pull/4, please have a try.     
However, I think a better way to manage `Go`'s dependency is always to use [Go Modules](https://github.com/golang/go/wiki/Modules).     
By the way, it seems that your codes are not aware of `Go` versions, so you can get rid of the `goversion: "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"` parameter if you'd like to. The default `Go` version for the building is `1.14`.

**Comment by BenjaminNavarro** [comment]
@wangyoucao577 Thanks! Yes I use go get to pull my dependencies usually. I didn't know about Go Modules (I didn't exist when I wrote this tool) so I'll check this out.

I merged you PR and everything went well except the push of the Windows AMD64 MD5 file that failed. The binary is okay though.

**Comment by wangyoucao577** [comment]
@BenjaminNavarro The error is due to unstable GitHub Assets API. It happens some times. If you create another release, most of time it will success. I may find other way to make it more stable(fix/avoid the unstable API issue) later.

**Comment by BenjaminNavarro** [comment]
@wangyoucao577 Ok thanks for the explanation and everything!
