### ISSUE TITLE
UPX support?

### ISSUE THREAD

**Issue by MaxUNof** [wangyoucao577/go-release-action#43]
Can you make support for automatic packing of executable files via [UPX](https://github.com/upx/upx)?

**Comment by wangyoucao577** [comment]
It looks meaningful. I'll think about how to support it.

**Comment by wangyoucao577** [comment]
Hi @MaxUNof, It's now ready on branch `feature/upx`. It'll be great if you can help to have a try before I merge the code since I'm not very familiar with the `upx`.                
Try out `uses: wangyoucao577/go-release-action@feature/upx` with additional param `executable_compression: upx -v`. You can plus any `upx` args here.        
Let me know if any question.

**Comment by MaxUNof** [comment]
Thank you!

**Comment by MaxUNof** [comment]
All works fine
