### ISSUE TITLE
CGO / XGO

### ISSUE THREAD

**Issue by karlseguin** [wangyoucao577/go-release-action#48]
Unless I'm mistake, this doesn't work if the project requires CGO. I'm curious if it would be possible to add support for this by liveraging xgo (https://github.com/karalabe/xgo) ?

**Comment by wangyoucao577** [comment]
I thought this before, but I was worried that the [xgo](https://github.com/karalabe/xgo) seems a little violent, which packages all the cross compilers/libraries together. Moreoever, it seems no upgrade in last 2 years, which has behind `Go`'s new versions already.        
On the other hand, I saw some smart guy used `pre_command` to install cross compilers so that `cgo` could be available. I think it's great since most of time when we want to cross compile we'll have special cross compiler/library requirement. This appoarch balances complexity and flexibility. Would you please have a try? Or would you please share more on your requirement, so that we can discuss more in detail.
