### ISSUE TITLE
packs folder when folder is the same name as binary

### ISSUE THREAD

**Issue by grosser** [wangyoucao577/go-release-action#9]
I tried to release https://github.com/wercker/stern but it has a folder called `stern` and the release ends up being the `stern` folder including a `stern/stern` executable :D
... so ideally build with a temp name and then rename after (I still want the binary to be called stern)
or explicitly only add the binary to the tar

**Comment by wangyoucao577** [comment]
Oh, I see. It'll be better if there's a way to avoid the name duplication. I'll try soon, probably use a tmp build folder to hold the built binary before compress. Will you be interested to have a try if I provide a temp version before release?

**Comment by grosser** [comment]
yeah sure!

**Comment by wangyoucao577** [comment]
@grosser  I have fixed the issue and released [v1.5](https://github.com/wangyoucao577/go-release-action/releases/tag/v1.5). I also created a [PR](https://github.com/grosser/stern/pull/1) for your workflow since I use it to test the behavior directly. Please merge it to have a try if it's ok for you.

**Comment by grosser** [comment]
awesome! :D
