### ISSUE TITLE
How to release artifact on every push?

### ISSUE THREAD

**Issue by Manjit2003** [wangyoucao577/go-release-action#90]
I just wanted to create a release on every push. How can this be done?

**Comment by wangyoucao577** [comment]
You'll need to set `release_tag` and `overwrite` at least. `release_tag` indicates where the assets upload to since no new `release` created.  `overwrite` tells to overwrite exist asserts since there usually be something exist on every push.        

https://github.com/chrislusf/seaweedfs/blob/master/.github/workflows/binaries_dev.yml shows an examples even though  more complex than usual.

**Comment by Manjit2003** [comment]
Thank you, @wangyoucao577 for your speedy reply. I got it. Closing
